import { Injectable, NotFoundException } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { PrismaService } from '../database/prisma.service';
import type {
  AttachmentCreateInput,
  AttachmentOwnershipInput,
  AttachmentRecord,
  AttachmentRepository,
  AttachmentScope,
} from './attachments.types';
import type { ImageAnalysis } from './image-analysis';

export const ATTACHMENT_REPOSITORY = Symbol('ATTACHMENT_REPOSITORY');

type Row = Record<string, unknown>;

type Delegate = {
  create(args: { data: Row }): Promise<Row>;
  findFirst(args: { where: Row }): Promise<Row | null>;
  findMany(args: { where: Row }): Promise<Row[]>;
  updateMany(args: { where: Row; data: Row }): Promise<{ count: number }>;
};

type RelatedDelegate = {
  findFirst(args: { where: Row; select?: Row }): Promise<Row | null>;
};

type RuntimeDataModel = {
  models?: Record<string, { fields?: Array<{ name: string }> }>;
};

/**
 * Prisma adapter kept deliberately narrow so the attachment feature can be
 * compiled while the generated client is being regenerated by another phase.
 * No `Prisma.Attachment*` types are imported here; the adapter only relies on
 * the small delegate surface it needs.
 */
@Injectable()
export class PrismaAttachmentRepository implements AttachmentRepository {
  constructor(private readonly prisma: PrismaService) {}

  async assertOwnership(scope: AttachmentScope, ownership: AttachmentOwnershipInput): Promise<void> {
    const shop = await this.related('shop').findFirst({
      where: { id: ownership.shopId, ...scopeWhere(scope) },
    });
    if (!shop) throw missing('SHOP_NOT_FOUND', 'shop not found');

    const buyer = await this.related('buyer').findFirst({
      // A Delete Customer Data command leaves the Buyer row only as an
      // anonymous aggregate anchor. It is never a valid owner for a new
      // attachment/object after anonymization.
      where: { id: ownership.buyerId, ...scopeWhere(scope), anonymizedAt: null },
    });
    if (!buyer) throw missing('BUYER_NOT_FOUND', 'buyer not found');

    if (ownership.conversationId) {
      const conversation = await this.related('conversation').findFirst({
        where: {
          id: ownership.conversationId,
          ...scopeWhere(scope),
          shopId: ownership.shopId,
          buyerId: ownership.buyerId,
        },
      });
      if (!conversation) throw missing('CONVERSATION_NOT_FOUND', 'conversation not found');
    }
  }

  async create(input: AttachmentCreateInput): Promise<AttachmentRecord> {
    const data: Row = {
      workspaceId: input.workspaceId,
      tenantId: input.tenantId,
      shopId: input.shopId,
      [this.attachmentKeyField()]: input.objectKey,
      mimeType: input.mimeType,
      size: input.size,
      status: input.status,
      containsPII: input.containsPII,
      ...(input.analysisJson === null ? {} : { analysisJson: input.analysisJson }),
      expiresAt: input.expiresAt,
      ...(input.createdAt ? { createdAt: input.createdAt } : {}),
    };
    if (this.supportsAttachmentField('buyerId')) data.buyerId = input.buyerId;
    if (input.conversationId && this.supportsAttachmentField('conversationId')) data.conversationId = input.conversationId;
    const row = await this.attachment().create({ data });
    return this.record(row);
  }

  async findById(scope: AttachmentScope, id: string): Promise<AttachmentRecord | null> {
    const row = await this.attachment().findFirst({
      where: { id, ...scopeWhere(scope) },
    });
    return row ? this.record(row) : null;
  }

  async markActive(scope: AttachmentScope, id: string, now: Date): Promise<AttachmentRecord | null> {
    const data: Row = { status: 'ACTIVE' };
    if (this.hasAttachmentField('updatedAt')) data.updatedAt = now;
    const activated = await this.attachment().updateMany({
      where: { id, ...scopeWhere(scope), status: 'PENDING' },
      data,
    });
    if (activated.count !== 1) return null;
    return this.findById(scope, id);
  }

  async markExpired(scope: AttachmentScope, id: string, now: Date): Promise<AttachmentRecord | null> {
    return this.updateStatus(scope, id, 'EXPIRED', now);
  }

  async markDeleted(scope: AttachmentScope, id: string, now: Date): Promise<AttachmentRecord | null> {
    return this.updateStatus(scope, id, 'DELETED', now);
  }

  private async updateStatus(
    scope: AttachmentScope,
    id: string,
    status: 'EXPIRED' | 'DELETED',
    now: Date,
  ): Promise<AttachmentRecord | null> {
    const data: Row = { status };
    if (this.hasAttachmentField('deletedAt')) data.deletedAt = now;
    if (this.hasAttachmentField('updatedAt')) data.updatedAt = now;
    const updated = await this.attachment().updateMany({
      where: { id, ...scopeWhere(scope), status: { in: ['PENDING', 'ACTIVE'] } },
      data,
    });
    if (updated.count !== 1) return null;
    return this.findById(scope, id);
  }

  async listExpired(now: Date): Promise<AttachmentRecord[]> {
    const rows = await this.attachment().findMany({
      where: { status: { in: ['PENDING', 'ACTIVE'] }, expiresAt: { lte: now } },
    });
    return rows.map((row) => this.record(row));
  }

  private attachment(): Delegate {
    return delegate(this.prisma, 'attachment');
  }

  private related(name: 'shop' | 'buyer' | 'conversation'): RelatedDelegate {
    return delegate(this.prisma, name) as RelatedDelegate;
  }

  private attachmentKeyField(): 'objectKey' | 'storageKey' {
    if (this.hasAttachmentField('objectKey')) return 'objectKey';
    if (this.hasAttachmentField('storageKey')) return 'storageKey';
    // Terra's Phase 03 model uses objectKey.  The fallback keeps unit fakes
    // that do not expose Prisma's runtime data model deterministic.
    return 'objectKey';
  }

  private hasAttachmentField(field: string): boolean {
    return this.attachmentFieldNames()?.has(field) ?? false;
  }

  private supportsAttachmentField(field: string): boolean {
    // When a fake or an older generated client does not expose DMMF metadata,
    // assume the Phase 03 fields exist.  A generated client with metadata can
    // safely omit fields from the pre-model compatibility branch.
    return this.attachmentFieldNames()?.has(field) ?? true;
  }

  private attachmentFieldNames(): Set<string> | undefined {
    const runtime = (this.prisma as unknown as { _runtimeDataModel?: RuntimeDataModel })._runtimeDataModel;
    const fields = runtime?.models?.Attachment?.fields;
    return fields ? new Set(fields.map((entry) => entry.name)) : undefined;
  }

  private record(row: Row): AttachmentRecord {
    const analysis = row.analysisJson;
    return {
      id: stringValue(row.id),
      workspaceId: stringValue(row.workspaceId),
      tenantId: stringValue(row.tenantId),
      shopId: stringValue(row.shopId),
      buyerId: stringValue(row.buyerId),
      conversationId: nullableString(row.conversationId),
      objectKey: stringValue(row.objectKey ?? row.storageKey),
      mimeType: stringValue(row.mimeType),
      size: numberValue(row.size),
      status: attachmentStatus(row.status),
      containsPII: Boolean(row.containsPII),
      analysisJson: analysis && typeof analysis === 'object' ? (analysis as ImageAnalysis) : null,
      expiresAt: dateValue(row.expiresAt),
      createdAt: dateValue(row.createdAt, new Date()),
      deletedAt: row.deletedAt ? dateValue(row.deletedAt) : null,
    };
  }
}

export type InMemoryAttachmentRepositoryOptions = {
  shops?: Array<{ id: string } & AttachmentScope>;
  buyers?: Array<{ id: string } & AttachmentScope>;
  conversations?: Array<{ id: string; shopId: string; buyerId: string } & AttachmentScope>;
  attachments?: AttachmentRecord[];
};

/** Deterministic repository test double with the same scope checks as Prisma. */
@Injectable()
export class InMemoryAttachmentRepository implements AttachmentRepository {
  private readonly attachmentRows = new Map<string, AttachmentRecord>();
  private readonly shops: NonNullable<InMemoryAttachmentRepositoryOptions['shops']>;
  private readonly buyers: NonNullable<InMemoryAttachmentRepositoryOptions['buyers']>;
  private readonly conversations: NonNullable<InMemoryAttachmentRepositoryOptions['conversations']>;

  constructor(options: InMemoryAttachmentRepositoryOptions = {}) {
    this.shops = options.shops ?? [];
    this.buyers = options.buyers ?? [];
    this.conversations = options.conversations ?? [];
    for (const row of options.attachments ?? []) this.attachmentRows.set(row.id, cloneRecord(row));
  }

  async assertOwnership(scope: AttachmentScope, ownership: AttachmentOwnershipInput): Promise<void> {
    if (
      this.shops.length > 0 &&
      !this.shops.some((entry) => entry.id === ownership.shopId && sameScope(entry, scope))
    ) {
      throw missing('SHOP_NOT_FOUND', 'shop not found');
    }
    if (
      this.buyers.length > 0 &&
      !this.buyers.some((entry) => entry.id === ownership.buyerId && sameScope(entry, scope))
    ) {
      throw missing('BUYER_NOT_FOUND', 'buyer not found');
    }
    if (
      ownership.conversationId &&
      this.conversations.length > 0 &&
      !this.conversations.some(
        (entry) =>
          entry.id === ownership.conversationId &&
          entry.shopId === ownership.shopId &&
          entry.buyerId === ownership.buyerId &&
          sameScope(entry, scope),
      )
    ) {
      throw missing('CONVERSATION_NOT_FOUND', 'conversation not found');
    }
  }

  async create(input: AttachmentCreateInput): Promise<AttachmentRecord> {
    const now = input.createdAt ?? new Date();
    const row: AttachmentRecord = {
      ...input,
      id: randomUUID(),
      createdAt: new Date(now),
      deletedAt: null,
      analysisJson: input.analysisJson ? structuredClone(input.analysisJson) : null,
      expiresAt: new Date(input.expiresAt),
    };
    this.attachmentRows.set(row.id, row);
    return cloneRecord(row);
  }

  async findById(scope: AttachmentScope, id: string): Promise<AttachmentRecord | null> {
    const row = this.attachmentRows.get(id);
    return row && sameScope(row, scope) ? cloneRecord(row) : null;
  }

  async markActive(scope: AttachmentScope, id: string, _now: Date): Promise<AttachmentRecord | null> {
    const row = this.attachmentRows.get(id);
    if (!row || !sameScope(row, scope) || row.status !== 'PENDING') return null;
    row.status = 'ACTIVE';
    return cloneRecord(row);
  }

  async markExpired(scope: AttachmentScope, id: string, now: Date): Promise<AttachmentRecord | null> {
    const row = this.attachmentRows.get(id);
    if (!row || !sameScope(row, scope) || (row.status !== 'PENDING' && row.status !== 'ACTIVE')) return null;
    row.status = 'EXPIRED';
    row.deletedAt = new Date(now);
    return cloneRecord(row);
  }

  async markDeleted(scope: AttachmentScope, id: string, now: Date): Promise<AttachmentRecord | null> {
    const row = this.attachmentRows.get(id);
    if (!row || !sameScope(row, scope) || (row.status !== 'PENDING' && row.status !== 'ACTIVE')) return null;
    row.status = 'DELETED';
    row.deletedAt = new Date(now);
    return cloneRecord(row);
  }

  async listExpired(now: Date): Promise<AttachmentRecord[]> {
    return [...this.attachmentRows.values()]
      .filter((row) => (row.status === 'PENDING' || row.status === 'ACTIVE') && row.expiresAt.getTime() <= now.getTime())
      .map(cloneRecord);
  }

  /** Test-only inspection that returns a defensive copy. */
  get(id: string): AttachmentRecord | undefined {
    const row = this.attachmentRows.get(id);
    return row ? cloneRecord(row) : undefined;
  }
}

function delegate(client: unknown, name: string): Delegate {
  const candidate = (client as Record<string, unknown>)[name];
  if (!candidate || typeof candidate !== 'object') {
    throw new Error(`ATTACHMENT_${name.toUpperCase()}_REPOSITORY_UNAVAILABLE`);
  }
  return candidate as Delegate;
}

function scopeWhere(scope: AttachmentScope): Row {
  return {
    workspaceId: scope.workspaceId,
    tenantId: scope.tenantId,
    ...(scope.shopId ? { shopId: scope.shopId } : {}),
    ...(scope.buyerId ? { buyerId: scope.buyerId } : {}),
  };
}

function sameScope(left: { workspaceId: string; tenantId: string; shopId?: string; buyerId?: string }, right: AttachmentScope): boolean {
  return (
    left.workspaceId === right.workspaceId &&
    left.tenantId === right.tenantId &&
    (!right.shopId || left.shopId === right.shopId) &&
    (!right.buyerId || left.buyerId === right.buyerId)
  );
}

function cloneRecord(row: AttachmentRecord): AttachmentRecord {
  return {
    ...row,
    expiresAt: new Date(row.expiresAt),
    createdAt: new Date(row.createdAt),
    deletedAt: row.deletedAt ? new Date(row.deletedAt) : null,
    analysisJson: row.analysisJson ? structuredClone(row.analysisJson) : null,
  };
}

function stringValue(value: unknown): string {
  return typeof value === 'string' ? value : String(value ?? '');
}

function nullableString(value: unknown): string | null {
  return value === null || value === undefined ? null : stringValue(value);
}

function numberValue(value: unknown): number {
  const result = typeof value === 'number' ? value : Number(value);
  return Number.isFinite(result) ? result : 0;
}

function dateValue(value: unknown, fallback?: Date): Date {
  if (value instanceof Date) return new Date(value);
  const date = value ? new Date(String(value)) : fallback;
  if (!date || Number.isNaN(date.getTime())) return fallback ? new Date(fallback) : new Date(0);
  return date;
}

function attachmentStatus(value: unknown): 'PENDING' | 'ACTIVE' | 'EXPIRED' | 'DELETED' {
  return value === 'PENDING' || value === 'EXPIRED' || value === 'DELETED' ? value : 'ACTIVE';
}

function missing(code: string, message: string): NotFoundException {
  return new NotFoundException({ code, message });
}
